version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: services/backend
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URL: mongodb://root:secret@mongo:27017/
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/usr/src/app
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    restart: unless-stopped